FROM ghcr.io/blinklabs-io/go:1.24.5-1 AS build

FROM ghcr.io/blinklabs-io/cardano-configs:20250213-1 AS cardano-configs
FROM ghcr.io/blinklabs-io/txtop:0.12.3 AS txtop

FROM debian:bookworm-slim AS goreleaser-test
COPY goreleaser-test /bin/
COPY --from=cardano-configs /config/ /opt/cardano/config/
COPY --from=txtop /bin/txtop /usr/local/bin/
ENTRYPOINT ["goreleaser-test"]
