# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserTest < Formula
  desc ""
  homepage "https://github.com/blinklabs-io/goreleaser-test"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blinklabs-io/goreleaser-test/releases/download/v0.1.0/goreleaser-test_0.1.0_darwin_x86_64.tar.gz"
      sha256 "d48a9414146490cb2a7e464b9c71bae91d6af50c2a16b0e90f5bd953353fd135"

      def install
        bin.install "goreleaser-test"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blinklabs-io/goreleaser-test/releases/download/v0.1.0/goreleaser-test_0.1.0_darwin_arm64.tar.gz"
      sha256 "1fd94915bc89d70617dc0276867d15395137cdd40dd67420e6430978f16b1690"

      def install
        bin.install "goreleaser-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blinklabs-io/goreleaser-test/releases/download/v0.1.0/goreleaser-test_0.1.0_linux_x86_64.tar.gz"
        sha256 "4cf3fb7af7f36c24d16ec018f0a9c612d5f24bdd8f20db7bf364a1dfca50b0d6"

        def install
          bin.install "goreleaser-test"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blinklabs-io/goreleaser-test/releases/download/v0.1.0/goreleaser-test_0.1.0_linux_arm64.tar.gz"
        sha256 "17efded59a0196ff883d51a58149f90791aacfdae0165e30dd0ac4165218c0d4"

        def install
          bin.install "goreleaser-test"
        end
      end
    end
  end
end
