# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserTest < Formula
  desc "Install goreleaser-test binaries"
  homepage "https://github.com/blinklabs-io/goreleaser-test"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blinklabs-io/goreleaser-test/releases/download/v0.3.0/goreleaser-test_0.3.0_darwin_x86_64.tar.gz"
      sha256 "b2fa1ae65c900173aeb0a44cd8587e567fa58d8776624b5ae4fe32effa846c16"

      def install
        bin.install "goreleaser-test"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blinklabs-io/goreleaser-test/releases/download/v0.3.0/goreleaser-test_0.3.0_darwin_arm64.tar.gz"
      sha256 "e061b34dffb6c3a1148ac33f610804d24c04a4dc3bf285fe449b83cb64103701"

      def install
        bin.install "goreleaser-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blinklabs-io/goreleaser-test/releases/download/v0.3.0/goreleaser-test_0.3.0_linux_x86_64.tar.gz"
        sha256 "659e2e9a93ffd1fde510048067213aab9f8bd77b92d081fb48c3c8dde72a5b52"

        def install
          bin.install "goreleaser-test"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blinklabs-io/goreleaser-test/releases/download/v0.3.0/goreleaser-test_0.3.0_linux_arm64.tar.gz"
        sha256 "31006d55e72ca5c5beb8401a3f4e0252dc96f94a4d5728e735cb9b2c4f8c6ea9"

        def install
          bin.install "goreleaser-test"
        end
      end
    end
  end
end
