# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserTest < Formula
  desc "Install goreleaser-test binaries"
  homepage "https://github.com/blinklabs-io/goreleaser-test"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blinklabs-io/goreleaser-test/releases/download/v0.1.1/goreleaser-test_0.1.1_darwin_x86_64.tar.gz"
      sha256 "39a3bf692e350c18406c82ac5735dfd532c99c1f8d7bb6ca8ca0ffe7af9e4e9d"

      def install
        bin.install "goreleaser-test"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blinklabs-io/goreleaser-test/releases/download/v0.1.1/goreleaser-test_0.1.1_darwin_arm64.tar.gz"
      sha256 "e57ee51e6e6df17bca36c43699eba25134635d5ff195b19a0af8e2fcf5d49afc"

      def install
        bin.install "goreleaser-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blinklabs-io/goreleaser-test/releases/download/v0.1.1/goreleaser-test_0.1.1_linux_x86_64.tar.gz"
        sha256 "d3ec8bda4c821b351e3250f4227acf9bd79e7e9de182ba1bf523c46bf6fb53de"

        def install
          bin.install "goreleaser-test"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blinklabs-io/goreleaser-test/releases/download/v0.1.1/goreleaser-test_0.1.1_linux_arm64.tar.gz"
        sha256 "021e98653bc011d39da4f085e7eca6b3b0ec0fa81d2f3a0219c31fcc6cd641c3"

        def install
          bin.install "goreleaser-test"
        end
      end
    end
  end
end
