name: go-test

on:
  push:
    tags:
      - v*
  pull_request:

permissions:
  contents: read

jobs:
  go-test:
    name: go-test
    strategy:
      matrix:
        go-version: [1.24.x]
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: go-test
        run: go test ./...
